This is makeindex, version 2.15 [TeX Live 2021] (kpathsea + Thai support).
Scanning style file ./kandidat.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file kandidat.acn....done (11 entries accepted, 0 rejected).
Sorting entries....done (43 comparisons).
Generating output file kandidat.acr....done (21 lines written, 0 warnings).
Output written in kandidat.acr.
Transcript written in kandidat.alg.
